### ISSUE TITLE
Permettre de construire les images de branches

### ISSUE THREAD

**Issue by gab9281** [ets-cfuhrman-pfe/EvalueTonSavoir#104]
Quel est la solution : 
 Permettre la creation d'image de branche pour toutes les branches du projet.
 
 Pourquoi? 
 Afin de permettre des tests d'intégration ainsi que de tests automatisés liés au déploiement docker. Ceci permet de tester que le binaire principal ( l'image docker ) se comporte bien et de valider la connexion avec des services externes. En effet, plusieurs api externes ne peuvent être utilisés dans des environement sans addresse url specifique, ce qui limite la capacité a faire des validations de ces services dans leur environnement de production.
  
Comment?
Ajouter une github action qui genere automatiquement des images aux releases et un toggle pour des branches spécifiques

**Comment by fuhrmanator** [comment]
Le "pourquoi" dans ton bogue as besoin de clarification (au moins pour moi). Je lance les tests automatisés sans image docker, par exemple. Est-ce pour faire les tests automatisé d'un environnement qui roule en docker (ça fait du sens, mais ce n'est pas précisé).
