### ISSUE TITLE
probleme interface de quiz

### ISSUE THREAD

**Issue by louis-antoine-etsmtl** [ets-cfuhrman-pfe/EvalueTonSavoir#17]
From ETS-PFE042-EvalueTonSavoir-Frontend created by [louis-antoine-etsmtl](https://github.com/louis-antoine-etsmtl): louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#56  

null

**Comment by louis-antoine-etsmtl** [comment]
les  fleches pour changer de question ne sont pas bien positionne et on devrais laisser plus despace entre chaques element de linterface

**Comment by fuhrmanator** [comment]
Il est difficile de comprendre les détails de cette issue faute de capture d'écran par exemple

**Comment by fuhrmanator** [comment]
Voici une capture d'écran sur desktop de ce que voit un étudiant:

![image](https://github.com/user-attachments/assets/35d8dcf2-45fe-40b9-87d1-0ae2d7ed2f33)

Version mobile (simulée dans Chrome avec gabarit iPhone dans Developer tools):

![image](https://github.com/user-attachments/assets/7b291e55-121f-4f52-a8c4-a1bfa4f785cb)

C'est assez acceptable -- j'ignore quel est le problème. Je vais fermer sauf si on peut me donner plus d'infos.

**Comment by fuhrmanator** [comment]
En effet il y plusieurs flèches pour naviguer
