### ISSUE TITLE
Several problems with account registration

### ISSUE THREAD

**Issue by louis-antoine-etsmtl** [ets-cfuhrman-pfe/EvalueTonSavoir#28]
From ETS-PFE042-EvalueTonSavoir-Frontend created by [fuhrmanator](https://github.com/fuhrmanator): louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#31  

**Describe the bug**
1. No feedback is given in the front-end to say an email about registration is sent. 
2. No confirmation of the email is done. I only received an email "Votre compte a été créé avec succès." It seems this could allow hackers to create accounts with no traceability, or even use fake email addresses. It's an insecure way to register. A modern, professional way should exist for this feature. 

**To Reproduce**

1. Register for a new account...

**Expected behavior**
I expect a "Check your email to verify your account" (or similar message).
I expect that I have to click a link to verify the account. 

Perhaps these points are moot if authentication will be done using ETS accounts?

**Comment by louis-antoine-etsmtl** [comment]
# What needs to be done

1. Implement feedback mechanism for account creation process.
2. Consider restricting account creation to ETS domains. Alternatively, integrate with the ETS login system for enhanced security.
    > Open Source Considerations: Integrating with a closed-source system may not align with project principles. Instead, opting for a simpler approach such as sending a confirmation email could suffice.

**Comment by laurentchounan** [comment]
Ceci n'est plus nécessaire car il y aura un SSO implémenté.
