### ISSUE TITLE
Configuration du serveur

### ISSUE THREAD

**Issue by louis-antoine-etsmtl** [ets-cfuhrman-pfe/EvalueTonSavoir#42]
From ETS-PFE042-EvalueTonSavoir-Frontend created by [louis-antoine-etsmtl](https://github.com/louis-antoine-etsmtl): louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#11  

null

**Comment by louis-antoine-etsmtl** [comment]
# Requis

- soit hosté dans des conteneur Docker (idéalement)
- avoir une BD mongoDB

**Comment by louis-antoine-etsmtl** [comment]
waiting on domain name

**Comment by fuhrmanator** [comment]
http://evalsa.etsmtl.ca (sans certificat) -- c'est déployé depuis quelques mois.
