### ISSUE TITLE
Info/documentation sur la BD est manquante

### ISSUE THREAD

**Issue by fuhrmanator** [ets-cfuhrman-pfe/EvalueTonSavoir#56]
Dans le wiki, je n'ai rien trouvé sauf https://github.com/louis-antoine-etsmtl/EvalueTonSavoir/wiki/D%C3%A9ploiement-D%C3%A9veloppement-Local#pr%C3%A9requis

> Ensuite, assurez-vous d'avoir accès à un serveur MongoDB de développement

Je pense qu'il faut minimalement décrire la BD.

**Comment by louis-antoine-etsmtl** [comment]
Est-ce vraiment nécessaire, car la base de données est créée automatiquement au démarrage de l'application. Tout ce que l'utilisateur a à faire est de fournir une connection à une base de données MongoDB

Si oui, je propose le suivant
```
Avant de commencer, assurez-vous d'avoir une instance MongoDB disponible pour le développement. 
Si vous n'en avez pas encore, vous pouvez installer MongoDB localement sur votre machine ou 
utiliser un service cloud comme MongoDB Atlas.
```

**Comment by fuhrmanator** [comment]
Je comprends que vous la considérer comme une boîte noire, mais il vaut mieux documenter un peu la philosophie de design, etc., (n'est-ce pas) pour l'équipe qui va reprendre le projet.

**Comment by louis-antoine-etsmtl** [comment]
Je n'avais pas compris l'issue comme ça. Oui en effet une page explicative de la philosophie et design de la base de données serait pertinente et un oubli de notre part. Ce sera ajouté.

**Comment by fuhrmanator** [comment]
J'ai ouvert la BD avec MongoDBCompass et on peut bien explorer. Par exemple, je vois un objet Quiz dans files:

```json
{
  "_id": {
    "$oid": "66da02fc85089061335777e8"
  },
  "folderId": "66da02dd85089061335777e7",
  "userId": "66da02a985089061335777e5",
  "title": "Titre",
  "content": [
    "Avec quoi ouvre-t-on une porte? { \n= clé \n= clef \n}// Permet de fournir plusieurs bonnes réponses. Note: Les majuscules ne sont pas prises en compte.",
    "Avec quoi ouvre-t-on une porte? { \n= clé \n= clef \n}// Permet de fournir plusieurs bonnes réponses. Note: Les majuscules ne sont pas prises en compte.",
    "Avec quoi ouvre-t-on une porte? { \n= clé \n= clef \n}// Permet de fournir plusieurs bonnes réponses. Note: Les majuscules ne sont pas prises en compte."
  ],
  "created_at": {
    "$date": "2024-09-05T19:14:04.869Z"
  },
  "updated_at": {
    "$date": "2024-09-05T19:14:04.869Z"
  }
}
```

**Comment by fuhrmanator** [comment]
Voici une capture d'écran de l'outil permettant de naviguer la BD:

![image](https://github.com/user-attachments/assets/3a79c280-af5d-4f46-990d-943c61a32abb)

**Comment by fuhrmanator** [comment]
Quant au stockage de la BD sur evalsa.etsmtl.ca, voir l'explication de ChatGPT selon le fichier docker-compose.yaml: https://github.com/ets-cfuhrman-pfe/EvalueTonSavoir/blob/ea9e9b9ada4eba8c2dc01a5c5f44ce4c5648c07d/docker-compose.yaml#L49

https://chatgpt.com/share/66e33f79-afd4-8013-ba26-a75a864ba258

> This indicates that mongodb_data is a named volume created and managed by Docker. Since external: false is specified, Docker will automatically create and manage this volume on the local machine running the Docker container, storing it in a Docker-specific directory on the host (by default under /var/lib/docker/volumes on Linux systems, or equivalent directories on other systems).
    
> The data is persisted across container restarts but is local to the machine running Docker unless explicitly mounted to an external directory.
