### ISSUE TITLE
Quiz exporté n'est pas du GIFT valide

### ISSUE THREAD

**Issue by louis-antoine-etsmtl** [ets-cfuhrman-pfe/EvalueTonSavoir#57]
Le format du fichier lors de l'exportation en format gift n'est pas exact. Il manque des retours de ligne pour qu'il soit conforme au standard.

**Comment by fuhrmanator** [comment]
Pour valdier l'export, vous pouvez faire un test qui essaie d'importer avec le parseur. S'il n'y a pas d'erreurs, ça passe (pas besoin de valider chaque élément importé). C'est un genre de "smoke test".
