### ISSUE TITLE
inline LaTeX

### ISSUE THREAD

**Issue by louis-antoine-etsmtl** [ets-cfuhrman-pfe/EvalueTonSavoir#58]
L'éditeur devrais permettre le LaTeX en ligne, mais permet seulement le LaTeX sur une ligne unique

**Comment by fuhrmanator** [comment]
Je pense que cela a été corrigé:

```
::Titre ici::[markdown]Formule sur une ligne\: $E\=mc^2$ suivie par une formule sur une ligné séparée\: $$E\=mc^2$$ {T}
```
![image](https://github.com/user-attachments/assets/626b84cd-c196-425b-b941-9d46e8cafd3c)
