### ISSUE TITLE
Affichage des matrice problématique : ajout de '&' entre les éléments.

### ISSUE THREAD

**Issue by GenevieveSavard** [ets-cfuhrman-pfe/EvalueTonSavoir#71]
Il y a un problème avec l'affichage des matrices: ajout de _**amp;**_ entre les éléments.
Par exemple avec les 3 questions suivantes, [qui sont pourtant bien affichées par l'éditeur de C. Fuhrman](https://fuhrmanator.github.io/GIFT-grammar-PEG.js/editor/editor.html?text=hL11JiCm4BplAqOYia1Gr0PwYPGR7-3kYnilnLAo1ST1G1J-qtVqOsn34o71iIDR6ktiUiPR58yTjodi1D8rXtqChntVD2x5K75R57ZOYV0dQeO_x1F79eYJ1C-e7KvzQBlmfbM-pJ9hDxmDOlkNKNot0vpPm2fG6Q-4nVzMimpzHRaSG7G6htiOtFsuvKfNV_skjLJpKxh4DErYT1zsi7rLgUvqRCghrEFumDoaGWpRvtGrvaQvoF6bvrpnrp1JRWKMAvXy_j0i_hz4bCinoteW8Xn1fpjpecy0).
```
::Question numérique,matrices:: 
Donnez le déterminant de la matrice suivante.$$\\begin\{pmatrix\}
   a&b \\\\
   c&d
\\end\{pmatrix\}
$$  {#=0}  
 
Donnez le déterminant de la matrice suivante.$$\\begin\{pmatrix\}
   4 & 3 \\\\
   2 & 1
\\end\{pmatrix\}
+
\\left(
\begin\{array\}\{cc\}
   a & b \\\\
   c & d
\end\{array\}
\\right)
$$ {
=-2 
~2
~0}  
 
Donnez le déterminant de la matrice suivante.$$\\begin\{pmatrix\}
5 & 2 & 1 \\\\
-1 &2& 3 \\\\
5 & 2 & 1
\\end\{pmatrix\}
$$ {
=0 
~2
~5}
```
<img width="462" alt="image" src="https://github.com/louis-antoine-etsmtl/EvalueTonSavoir/assets/45633294/00590218-e9c3-4b14-bea
![image](https://github.com/louis-antoine-etsmtl/EvalueTonSavoir/assets/45633294/ff9d428d-e6bf-4411-afaa-d5ef3d3e7ee0)
c-955c5d3785b2">

Edit: image
![image](https://github.com/user-attachments/assets/a19b1994-b755-48a2-9ba4-a3c407a650fe)

**Comment by fuhrmanator** [comment]
Je rajoute une capture d'écran de ce qu'on voit dans evalsa.etsmtl.ca:
![image](https://github.com/user-attachments/assets/17192357-9b74-4214-b311-026ed263caf8)

**Comment by fuhrmanator** [comment]
@GenevieveSavard voici le résultat après avoir corrigé le bogue:
![image](https://github.com/user-attachments/assets/29c5de60-221a-4110-8ab9-a915460263ae)

La nouvelle image devrait se rendre au serveur demain matin à 5h...

**Comment by GenevieveSavard** [comment]
Très jolies matrices!

***@***.***

Merci,

Geneviève

De : Christopher (Cris) Fuhrman ***@***.***>
Envoyé : 14 septembre 2024 11:53
À : ets-cfuhrman-pfe/EvalueTonSavoir ***@***.***>
Cc : Savard, Geneviève ***@***.***>; Mention ***@***.***>
Objet : Re: [ets-cfuhrman-pfe/EvalueTonSavoir] Affichage des matrice problématique : ajout de '&' entre les éléments. (Issue #71)

[ATTENTION : Ce courriel provient de l'extérieur de l'ÉTS]
Évitez de cliquer sur un lien ou d'ouvrir une pièce jointe si vous ne connaissez pas l'expéditeur du courriel. En cas de doute, veuillez SVP créer un billet Problème de courriel au GUS<https://gus.etsmtl.ca/c2atom/LoginAzure?landingPage=/portal-request-form/714d9e14-bc17-47b8-a0e6-e154184ecbc2> .



@GenevieveSavard<https://github.com/GenevieveSavard> voici le résultat après avoir corrigé le bogue:
image.png (view on web)<https://github.com/user-attachments/assets/29c5de60-221a-4110-8ab9-a915460263ae>

La nouvelle image devrait se rendre au serveur demain matin à 5h...

-
